spring:
  profiles:
    active: development
  application:
    name: "%APP_NAME%"
    version: "%APP_VERSION%"
    build:
      time: "%APP_BUILD_TIME%"
      os:
        name: "%APP_BUILD_OS_NAME%"
        version: "%APP_BUILD_OS_VERSION%"

management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always
      access: read_only
    info:
      access: read_only

influxdb:
  bucket: device-data
  org: hlaeja_ltd

---
###############################
### Development environment ###
###############################
spring:
  config:
    activate:
      on-profile: development

influxdb:
  token: %INFLUXDB_TOKEN%
  url: http://localhost:8086

---
##########################
### Docker environment ###
##########################
spring:
  config:
    activate:
      on-profile: docker

influxdb:
  url: http://InfluxDB:8086

---
##############################
### Production environment ###
##############################
spring:
  config:
    activate:
      on-profile: production
